### Get all users with valid authorization
GET http://localhost:5083/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwianRpIjoiZWRiNmYyMTctYzJjYi00ODIyLWE2YzEtYTQ4NjBlZjg0YTA5IiwiZXhwIjo0ODk1OTUxODY0LCJpc3MiOiJNeUFQSSIsImF1ZCI6Ik15QVBJVXNlcnMifQ.SRiH_Q7EN0Q0r0UjdEVaUy3jbmpjyPgKJcfSfxp3cF4

### Get a single user by ID with valid authorization
GET http://localhost:5083/users/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwianRpIjoiZWRiNmYyMTctYzJjYi00ODIyLWE2YzEtYTQ4NjBlZjg0YTA5IiwiZXhwIjo0ODk1OTUxODY0LCJpc3MiOiJNeUFQSSIsImF1ZCI6Ik15QVBJVXNlcnMifQ.SRiH_Q7EN0Q0r0UjdEVaUy3jbmpjyPgKJcfSfxp3cF4

### Create a new user with valid authorization
POST http://localhost:5083/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwianRpIjoiZWRiNmYyMTctYzJjYi00ODIyLWE2YzEtYTQ4NjBlZjg0YTA5IiwiZXhwIjo0ODk1OTUxODY0LCJpc3MiOiJNeUFQSSIsImF1ZCI6Ik15QVBJVXNlcnMifQ.SRiH_Q7EN0Q0r0UjdEVaUy3jbmpjyPgKJcfSfxp3cF4

{
    "username": "Jerry Smerry",
    "emailaddress": "john.doe@example.com"
}

### Update an existing user with valid authorization
PUT http://localhost:5083/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwianRpIjoiZWRiNmYyMTctYzJjYi00ODIyLWE2YzEtYTQ4NjBlZjg0YTA5IiwiZXhwIjo0ODk1OTUxODY0LCJpc3MiOiJNeUFQSSIsImF1ZCI6Ik15QVBJVXNlcnMifQ.SRiH_Q7EN0Q0r0UjdEVaUy3jbmpjyPgKJcfSfxp3cF4

{
    "username": "John Doe Updated",
    "emailaddress": "john.doe.updated@example.com"
}

### Delete a user with valid authorization
DELETE http://localhost:5083/users/3
Accept: application/json
Authorization: Bearer 12eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwianRpIjoiOTI3YjMzYmQtMTFhOS00ZGUxLWFkZDItOTM5YTMxZmJkZWRjIiwiZXhwIjo0ODk1OTUyMTAzLCJpc3MiOiJNeUFQSSIsImF1ZCI6Ik15QVBJVXNlcnMifQ.CI2n7ctqzDgoAuC1CydzGvGONuXXvUjNRimxIDw4IRU

### Generate a new token
POST http://localhost:5083/generateToken
